import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import PickCard from "@/components/PickCard";
import { Skeleton } from "@/components/ui/skeleton";
import { Copy, Trophy, SortAsc, Filter } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface Pick {
  id: number; sport: string; player: string; team: string; opponent: string;
  market: string; line: number; side: string; confidence: number; ev: number;
  edge: string; reasoning: string; gameTime: string; status: string; createdAt: number;
}

type SortKey = "confidence" | "ev" | "createdAt";
type Filter = "all" | "elite" | "high" | "over" | "under";

export default function SportPage({ sport }: { sport: string }) {
  const { toast } = useToast();
  const [sort, setSort] = useState<SortKey>("confidence");
  const [filter, setFilter] = useState<Filter>("all");

  const { data: picks = [], isLoading } = useQuery<Pick[]>({
    queryKey: ["/api/picks", sport],
    queryFn: () => apiRequest("GET", `/api/picks?sport=${sport}&limit=50`).then(r => r.json()),
    refetchInterval: 45000,
  });

  const sportColor: Record<string, string> = {
    MLB: "text-red-400", NBA: "text-orange-400", NHL: "text-blue-400", Tennis: "text-green-400",
  };

  // Filter
  let filtered = [...picks];
  if (filter === "elite") filtered = filtered.filter(p => p.edge === "elite");
  else if (filter === "high") filtered = filtered.filter(p => p.edge === "elite" || p.edge === "high");
  else if (filter === "over") filtered = filtered.filter(p => p.side === "Over");
  else if (filter === "under") filtered = filtered.filter(p => p.side === "Under");

  // Sort
  filtered.sort((a, b) => {
    if (sort === "confidence") return b.confidence - a.confidence;
    if (sort === "ev") return b.ev - a.ev;
    return b.createdAt - a.createdAt;
  });

  const top6 = picks.filter(p => p.status === "pending").sort((a, b) => b.confidence - a.confidence).slice(0, 6);

  const copyAll6 = () => {
    const lines = top6.map((p, i) =>
      `${i + 1}. ${p.sport} | ${p.player} — ${p.side} ${p.line} ${p.market} (${p.confidence}% / +${p.ev}% EV)`
    ).join("\n");
    navigator.clipboard.writeText(`PropEdge Top 6 ${sport} Picks\n${"─".repeat(40)}\n${lines}\n\nGenerated by PropEdge AI`);
    toast({ title: "Top 6 Copied!", description: `${sport} picks copied to clipboard.` });
  };

  return (
    <div className="p-6 max-w-screen-xl mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between mb-5 flex-wrap gap-3">
        <div>
          <h1 className={`text-xl font-bold ${sportColor[sport]}`}>{sport} Props</h1>
          <p className="text-sm text-muted-foreground">AI-generated picks · auto-updating</p>
        </div>
        <button onClick={copyAll6}
          data-testid="copy-top-6"
          className="flex items-center gap-2 bg-amber-400 text-black font-bold text-sm px-4 py-2 rounded-xl hover:bg-amber-300 transition-colors">
          <Copy className="w-4 h-4" />
          Copy Top 6
        </button>
      </div>

      {/* Top 6 strip */}
      {top6.length > 0 && (
        <div className="bg-card border border-border rounded-xl p-4 mb-5">
          <div className="flex items-center gap-2 mb-3">
            <Trophy className="w-4 h-4 text-amber-400" />
            <span className="text-sm font-bold text-foreground">Top 6 for {sport}</span>
            <span className="text-[10px] text-muted-foreground ml-auto">tap any row to copy</span>
          </div>
          <div className="space-y-2">
            {top6.map((pick, i) => (
              <button key={pick.id}
                data-testid={`top6-row-${pick.id}`}
                onClick={() => {
                  const text = `${pick.side} ${pick.line} ${pick.market} — ${pick.player} (${pick.confidence}% / +${pick.ev}% EV)`;
                  navigator.clipboard.writeText(text);
                  toast({ description: "Copied to clipboard!" });
                }}
                className="w-full flex items-center gap-3 p-2 rounded-lg hover:bg-secondary transition-colors text-left">
                <span className="w-5 h-5 rounded-full bg-amber-400/20 text-amber-400 text-[10px] font-bold flex items-center justify-center shrink-0">{i + 1}</span>
                <span className="text-sm font-semibold text-foreground min-w-0 truncate">{pick.player}</span>
                <span className={`text-sm font-black ml-auto shrink-0 ${pick.side === "Over" ? "side-over" : "side-under"}`}>{pick.side} {pick.line}</span>
                <span className="text-xs text-muted-foreground shrink-0 hidden sm:inline">{pick.market}</span>
                <span className="text-[10px] text-green-400 font-bold shrink-0">+{pick.ev}%</span>
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Filters + sort */}
      <div className="flex items-center gap-2 mb-4 flex-wrap">
        <span className="text-xs text-muted-foreground flex items-center gap-1"><Filter className="w-3 h-3" /> Filter:</span>
        {(["all", "elite", "high", "over", "under"] as Filter[]).map(f => (
          <button key={f} onClick={() => setFilter(f)}
            className={`text-xs px-3 py-1 rounded-full border transition-colors capitalize
              ${filter === f ? "bg-amber-400/20 text-amber-400 border-amber-400/40" : "border-border text-muted-foreground hover:text-foreground"}`}>
            {f}
          </button>
        ))}
        <div className="ml-auto flex items-center gap-2">
          <span className="text-xs text-muted-foreground flex items-center gap-1"><SortAsc className="w-3 h-3" /> Sort:</span>
          {([["confidence", "Confidence"], ["ev", "EV+"], ["createdAt", "Newest"]] as [SortKey, string][]).map(([key, label]) => (
            <button key={key} onClick={() => setSort(key)}
              className={`text-xs px-3 py-1 rounded-full border transition-colors
                ${sort === key ? "bg-secondary text-foreground border-border" : "border-transparent text-muted-foreground hover:text-foreground"}`}>
              {label}
            </button>
          ))}
        </div>
      </div>

      {/* Picks grid */}
      {isLoading ? (
        <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-4">
          {Array(6).fill(0).map((_, i) => <Skeleton key={i} className="h-44 rounded-xl" />)}
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-4">
          {filtered.map((pick, i) => (
            <PickCard key={pick.id} pick={pick} rank={sort === "confidence" ? i + 1 : undefined} />
          ))}
          {filtered.length === 0 && (
            <div className="col-span-full text-center py-12 text-muted-foreground text-sm">
              No picks match this filter. AI is generating more…
            </div>
          )}
        </div>
      )}
    </div>
  );
}
