import { useState } from "react";
import { Copy, Trash2, X, ChevronDown, ChevronUp, Layers, ExternalLink } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

// ─── Types ────────────────────────────────────────────────────────────────────
export interface SlipPick {
  id: number;
  player: string;
  team: string;
  market: string;
  line: number;
  side: string;
  sport: string;
  confidence: number;
  ev: number;
}

// ─── Format helpers ───────────────────────────────────────────────────────────
function formatPrizePicks(picks: SlipPick[]): string {
  const lines = picks.map(p =>
    `${p.player} — ${p.side} ${p.line} ${p.market}`
  );
  return [
    `🎯 PrizePicks Lineup (${picks.length}-Pick)`,
    "─────────────────────────",
    ...lines,
    "",
    `Avg Confidence: ${Math.round(picks.reduce((s, p) => s + p.confidence, 0) / picks.length)}%`,
    "Generated by PropEdge AI"
  ].join("\n");
}

function formatUnderdog(picks: SlipPick[]): string {
  const lines = picks.map(p =>
    `${p.player} ${p.side.toUpperCase()} ${p.line} ${p.market} (${p.team})`
  );
  return [
    `🐶 Underdog Fantasy Lineup (${picks.length} Picks)`,
    "─────────────────────────",
    ...lines,
    "",
    `Avg EV: +${(picks.reduce((s, p) => s + p.ev, 0) / picks.length).toFixed(1)}%`,
    "Generated by PropEdge AI"
  ].join("\n");
}

function formatFanDuel(picks: SlipPick[]): string {
  const lines = picks.map(p =>
    `${p.player} | ${p.market} | ${p.side} ${p.line} | ${p.sport}`
  );
  return [
    `🏆 FanDuel Picks (${picks.length})`,
    "─────────────────────────",
    ...lines,
    "",
    "Generated by PropEdge AI"
  ].join("\n");
}

// ─── Platform Button ──────────────────────────────────────────────────────────
function PlatformBtn({
  label,
  icon,
  color,
  border,
  onClick,
  disabled,
}: {
  label: string;
  icon: string;
  color: string;
  border: string;
  onClick: () => void;
  disabled: boolean;
}) {
  return (
    <button
      onClick={onClick}
      disabled={disabled}
      data-testid={`export-${label.toLowerCase().replace(/\s/g, "-")}`}
      className="flex items-center gap-2 w-full px-3 py-2.5 rounded-xl text-xs font-bold transition-all disabled:opacity-40 hover:opacity-80 active:scale-[0.98]"
      style={{ background: color, border: `1px solid ${border}` }}
    >
      <span className="text-sm">{icon}</span>
      <span className="flex-1 text-left">Copy for {label}</span>
      <Copy className="w-3 h-3 opacity-70" />
    </button>
  );
}

// ─── Slip Pick Row ────────────────────────────────────────────────────────────
function SlipRow({ pick, onRemove }: { pick: SlipPick; onRemove: () => void }) {
  return (
    <div
      className="flex items-center gap-2 px-2.5 py-2 rounded-xl"
      style={{ background: "hsl(222 35% 10%)", border: "1px solid hsl(222 30% 15%)" }}
    >
      <div className="flex-1 min-w-0">
        <div className="text-xs font-bold text-foreground truncate">{pick.player}</div>
        <div className="text-[10px] text-muted-foreground truncate">
          <span className={pick.side === "Over" ? "text-lime-400 font-semibold" : "text-red-400 font-semibold"}>
            {pick.side}
          </span>{" "}
          {pick.line} {pick.market}
        </div>
      </div>
      <button
        onClick={onRemove}
        className="p-1 rounded-lg hover:bg-red-500/10 hover:text-red-400 text-muted-foreground transition-colors shrink-0"
        title="Remove pick"
      >
        <X className="w-3 h-3" />
      </button>
    </div>
  );
}

// ─── Main LineupSlip ──────────────────────────────────────────────────────────
interface LineupSlipProps {
  picks: SlipPick[];
  onRemove: (id: number) => void;
  onClear: () => void;
}

export default function LineupSlip({ picks, onRemove, onClear }: LineupSlipProps) {
  const { toast } = useToast();
  const [collapsed, setCollapsed] = useState(false);
  const [showExport, setShowExport] = useState(false);

  if (picks.length === 0) return null;

  const copyFor = (platform: string, formatter: (p: SlipPick[]) => string) => {
    navigator.clipboard.writeText(formatter(picks));
    toast({
      title: `Copied for ${platform}!`,
      description: `${picks.length} pick${picks.length > 1 ? "s" : ""} formatted & ready to paste.`,
    });
  };

  return (
    <div
      data-testid="lineup-slip"
      className="fixed bottom-5 right-5 z-50 w-72 rounded-2xl overflow-hidden shadow-2xl"
      style={{
        background: "hsl(222 47% 5%)",
        border: "1px solid hsl(258 90% 66% / 0.35)",
        boxShadow: "0 0 40px hsl(258 90% 66% / 0.12), 0 4px 32px rgba(0,0,0,0.6)",
      }}
    >
      {/* Header */}
      <div
        className="flex items-center gap-2 px-3 py-2.5 cursor-pointer select-none"
        style={{ background: "hsl(258 90% 66% / 0.1)", borderBottom: "1px solid hsl(258 90% 66% / 0.2)" }}
        onClick={() => setCollapsed(c => !c)}
      >
        <Layers className="w-3.5 h-3.5" style={{ color: "hsl(258 90% 75%)" }} />
        <span className="text-xs font-black tracking-wide" style={{ color: "hsl(258 90% 80%)" }}>
          MY LINEUP SLIP
        </span>
        <span
          className="ml-auto text-[9px] font-bold px-2 py-0.5 rounded-full"
          style={{ background: "hsl(258 90% 66% / 0.2)", color: "hsl(258 90% 80%)", border: "1px solid hsl(258 90% 66% / 0.3)" }}
        >
          {picks.length}/6
        </span>
        <button
          className="p-0.5 rounded hover:text-foreground text-muted-foreground transition-colors"
          onClick={(e) => { e.stopPropagation(); setCollapsed(c => !c); }}
        >
          {collapsed ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
        </button>
      </div>

      {!collapsed && (
        <div className="p-2.5 space-y-2">
          {/* Picks */}
          <div className="space-y-1.5">
            {picks.map(p => (
              <SlipRow key={p.id} pick={p} onRemove={() => onRemove(p.id)} />
            ))}
          </div>

          {picks.length < 6 && (
            <p className="text-[9px] text-muted-foreground text-center py-0.5">
              {6 - picks.length} more pick{6 - picks.length !== 1 ? "s" : ""} to fill the slip
            </p>
          )}

          {/* Export toggle */}
          <button
            data-testid="toggle-export"
            onClick={() => setShowExport(s => !s)}
            className="w-full flex items-center justify-center gap-1.5 py-2 rounded-xl text-xs font-bold transition-all"
            style={{
              background: "linear-gradient(135deg, hsl(258 90% 60%), hsl(220 90% 55%))",
              color: "#fff",
            }}
          >
            <ExternalLink className="w-3 h-3" />
            Export to Platform
            {showExport ? <ChevronUp className="w-3 h-3 ml-auto" /> : <ChevronDown className="w-3 h-3 ml-auto" />}
          </button>

          {/* Platform buttons */}
          {showExport && (
            <div className="space-y-1.5">
              <p className="text-[9px] text-muted-foreground text-center pb-0.5">
                One-tap copy → paste directly into the app
              </p>
              <PlatformBtn
                label="PrizePicks"
                icon="🎯"
                color="hsl(231 88% 18% / 0.8)"
                border="hsl(231 88% 50% / 0.4)"
                disabled={picks.length === 0}
                onClick={() => copyFor("PrizePicks", formatPrizePicks)}
              />
              <PlatformBtn
                label="Underdog"
                icon="🐶"
                color="hsl(22 95% 30% / 0.6)"
                border="hsl(22 95% 55% / 0.4)"
                disabled={picks.length === 0}
                onClick={() => copyFor("Underdog", formatUnderdog)}
              />
              <PlatformBtn
                label="FanDuel"
                icon="🏆"
                color="hsl(145 60% 15% / 0.7)"
                border="hsl(145 60% 45% / 0.4)"
                disabled={picks.length === 0}
                onClick={() => copyFor("FanDuel", formatFanDuel)}
              />
              <button
                data-testid="copy-all-generic"
                onClick={() => {
                  const text = picks.map((p, i) =>
                    `${i + 1}. ${p.player} — ${p.side} ${p.line} ${p.market} (${p.sport})`
                  ).join("\n");
                  navigator.clipboard.writeText(`PropEdge Lineup\n───────────────\n${text}\n\nGenerated by PropEdge AI`);
                  toast({ description: "Plain text lineup copied!" });
                }}
                className="w-full flex items-center justify-center gap-1.5 py-2 rounded-xl text-xs font-semibold transition-all hover:opacity-80"
                style={{
                  background: "hsl(222 35% 11%)",
                  border: "1px solid hsl(222 30% 18%)",
                  color: "hsl(222 20% 60%)",
                }}
              >
                <Copy className="w-3 h-3" />
                Copy Plain Text
              </button>
            </div>
          )}

          {/* Clear */}
          <button
            data-testid="clear-slip"
            onClick={onClear}
            className="w-full flex items-center justify-center gap-1.5 py-1.5 rounded-xl text-[10px] font-semibold text-muted-foreground hover:text-red-400 transition-colors"
          >
            <Trash2 className="w-3 h-3" />
            Clear Slip
          </button>
        </div>
      )}
    </div>
  );
}
