import { useState } from "react";
import { Copy, Trash2, X, ChevronDown, ChevronUp, Layers, ExternalLink, CheckCircle2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

// ─── Types ────────────────────────────────────────────────────────────────────
export interface SlipPick {
  id: number;
  player: string;
  team: string;
  market: string;
  line: number;
  side: string;
  sport: string;
  confidence: number;
  ev: number;
}

// ─── Platform configs ─────────────────────────────────────────────────────────
const PLATFORMS = [
  {
    id: "prizepicks",
    label: "PrizePicks",
    icon: "🎯",
    url: "https://app.prizepicks.com/board",
    color: "hsl(231 88% 18% / 0.85)",
    border: "hsl(231 88% 55% / 0.5)",
    textColor: "#a5b4fc",
    format: (picks: SlipPick[]) =>
      picks.map(p => `${p.player} ${p.side} ${p.line}`).join("\n"),
  },
  {
    id: "underdog",
    label: "Underdog Fantasy",
    icon: "🐶",
    url: "https://underdogfantasy.com/pick-em",
    color: "hsl(22 95% 22% / 0.85)",
    border: "hsl(22 95% 55% / 0.5)",
    textColor: "#fdba74",
    format: (picks: SlipPick[]) =>
      picks.map(p => `${p.player} ${p.side === "Over" ? "Higher" : "Lower"} ${p.line} ${p.market}`).join("\n"),
  },
  {
    id: "fanduel",
    label: "FanDuel",
    icon: "🏆",
    url: "https://www.fanduel.com/sports-betting",
    color: "hsl(145 60% 12% / 0.85)",
    border: "hsl(145 60% 45% / 0.5)",
    textColor: "#86efac",
    format: (picks: SlipPick[]) =>
      picks.map(p => `${p.player} ${p.side} ${p.line} ${p.market} (${p.sport})`).join("\n"),
  },
];

// ─── Copy helper — tries modern API then legacy execCommand ───────────────────
async function copyToClipboard(text: string): Promise<boolean> {
  // Modern Clipboard API (requires HTTPS + user gesture)
  if (navigator.clipboard && window.isSecureContext) {
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch {
      // fall through to legacy
    }
  }
  // Legacy execCommand fallback
  try {
    const ta = document.createElement("textarea");
    ta.value = text;
    ta.setAttribute("readonly", "");
    ta.style.cssText = "position:fixed;top:0;left:0;opacity:0;pointer-events:none;";
    document.body.appendChild(ta);
    ta.focus();
    ta.select();
    const ok = document.execCommand("copy");
    document.body.removeChild(ta);
    return ok;
  } catch {
    return false;
  }
}

// ─── Platform export section ──────────────────────────────────────────────────
function ExportPanel({ picks }: { picks: SlipPick[] }) {
  const { toast } = useToast();
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [fallback, setFallback] = useState<{ text: string; url: string; label: string } | null>(null);

  const handlePlatform = async (platform: typeof PLATFORMS[0]) => {
    const formatted = platform.format(picks);

    // Always try to copy BEFORE opening tab (must be in same user gesture)
    const ok = await copyToClipboard(formatted);

    if (ok) {
      // Copy succeeded — now open the tab
      window.open(platform.url, "_blank", "noopener,noreferrer");
      setCopiedId(platform.id);
      toast({
        title: `Opening ${platform.label}`,
        description: `${picks.length} pick${picks.length !== 1 ? "s" : ""} copied — just paste when you arrive!`,
      });
      setTimeout(() => setCopiedId(null), 3500);
    } else {
      // Clipboard blocked — show text inline so user can select+copy manually
      setFallback({ text: formatted, url: platform.url, label: platform.label });
      toast({
        title: "Clipboard blocked by browser",
        description: "Select all the text below, copy it, then tap Open to launch the app.",
      });
    }
  };

  const handlePlain = async () => {
    const text = picks
      .map((p, i) => `${i + 1}. ${p.player} — ${p.side} ${p.line} ${p.market} (${p.sport})`)
      .join("\n");
    const full = `PropEdge Lineup\n───────────────\n${text}\n\nGenerated by PropEdge AI`;
    const ok = await copyToClipboard(full);
    if (ok) {
      setCopiedId("plain");
      toast({ description: "Plain text lineup copied!" });
      setTimeout(() => setCopiedId(null), 2500);
    } else {
      setFallback({ text: full, url: "", label: "Plain Text" });
    }
  };

  // ── Fallback: show selectable text ──
  if (fallback) {
    return (
      <div className="space-y-2">
        <div
          className="rounded-xl p-2.5 space-y-2"
          style={{ background: "hsl(222 35% 9%)", border: "1px solid hsl(258 90% 66% / 0.25)" }}
        >
          <p className="text-[10px] font-semibold" style={{ color: "hsl(258 90% 75%)" }}>
            Select all → copy → paste into {fallback.label}
          </p>
          <textarea
            readOnly
            defaultValue={fallback.text}
            onFocus={e => e.target.select()}
            rows={picks.length + 2}
            className="w-full text-[10px] font-mono rounded-lg p-2 resize-none focus:outline-none"
            style={{
              background: "hsl(222 40% 7%)",
              border: "1px solid hsl(222 30% 18%)",
              color: "hsl(222 20% 80%)",
            }}
          />
          <div className="flex gap-1.5">
            {fallback.url && (
              <button
                onClick={() => window.open(fallback.url, "_blank", "noopener,noreferrer")}
                className="flex-1 flex items-center justify-center gap-1.5 py-2 rounded-xl text-xs font-bold"
                style={{
                  background: "linear-gradient(135deg, hsl(258 90% 60%), hsl(220 90% 55%))",
                  color: "#fff",
                }}
              >
                <ExternalLink className="w-3 h-3" />
                Open {fallback.label}
              </button>
            )}
            <button
              onClick={() => setFallback(null)}
              className="px-3 py-2 rounded-xl text-xs font-semibold text-muted-foreground hover:text-foreground transition-colors"
              style={{ background: "hsl(222 35% 11%)", border: "1px solid hsl(222 30% 18%)" }}
            >
              Back
            </button>
          </div>
        </div>
      </div>
    );
  }

  // ── Normal export buttons ──
  return (
    <div className="space-y-1.5">
      <p className="text-[9px] text-center pb-0.5" style={{ color: "hsl(258 90% 75%)" }}>
        Copies picks + opens app in one tap
      </p>
      {PLATFORMS.map(platform => {
        const isCopied = copiedId === platform.id;
        return (
          <button
            key={platform.id}
            onClick={() => handlePlatform(platform)}
            disabled={picks.length === 0}
            data-testid={`export-${platform.id}`}
            className="flex items-center gap-2.5 w-full px-3 py-2.5 rounded-xl text-xs font-bold transition-all disabled:opacity-40 hover:brightness-110 active:scale-[0.98]"
            style={{
              background: platform.color,
              border: `1px solid ${platform.border}`,
              color: platform.textColor,
            }}
          >
            <span className="text-base leading-none">{platform.icon}</span>
            <span className="flex-1 text-left">
              {isCopied ? "Copied! Now paste in the app" : `Open ${platform.label}`}
            </span>
            {isCopied
              ? <CheckCircle2 className="w-3.5 h-3.5 shrink-0" />
              : <ExternalLink className="w-3.5 h-3.5 shrink-0 opacity-70" />
            }
          </button>
        );
      })}

      {/* Plain copy */}
      <button
        data-testid="copy-all-generic"
        onClick={handlePlain}
        className="w-full flex items-center justify-center gap-1.5 py-2 rounded-xl text-xs font-semibold transition-all hover:opacity-80"
        style={{
          background: "hsl(222 35% 11%)",
          border: "1px solid hsl(222 30% 18%)",
          color: "hsl(222 20% 60%)",
        }}
      >
        {copiedId === "plain"
          ? <><CheckCircle2 className="w-3 h-3 text-lime-400" /> Copied!</>
          : <><Copy className="w-3 h-3" /> Copy Plain Text</>
        }
      </button>
    </div>
  );
}

// ─── Slip Pick Row ────────────────────────────────────────────────────────────
function SlipRow({ pick, onRemove }: { pick: SlipPick; onRemove: () => void }) {
  return (
    <div
      className="flex items-center gap-2 px-2.5 py-2 rounded-xl"
      style={{ background: "hsl(222 35% 10%)", border: "1px solid hsl(222 30% 15%)" }}
    >
      <div className="flex-1 min-w-0">
        <div className="text-xs font-bold text-foreground truncate">{pick.player}</div>
        <div className="text-[10px] text-muted-foreground truncate">
          <span className={pick.side === "Over" ? "text-lime-400 font-semibold" : "text-red-400 font-semibold"}>
            {pick.side}
          </span>{" "}
          {pick.line} {pick.market}
        </div>
      </div>
      <button
        onClick={onRemove}
        className="p-1 rounded-lg hover:bg-red-500/10 hover:text-red-400 text-muted-foreground transition-colors shrink-0"
        title="Remove pick"
      >
        <X className="w-3 h-3" />
      </button>
    </div>
  );
}

// ─── Main LineupSlip ──────────────────────────────────────────────────────────
interface LineupSlipProps {
  picks: SlipPick[];
  onRemove: (id: number) => void;
  onClear: () => void;
}

export default function LineupSlip({ picks, onRemove, onClear }: LineupSlipProps) {
  const [collapsed, setCollapsed] = useState(false);
  const [showExport, setShowExport] = useState(false);

  if (picks.length === 0) return null;

  return (
    <div
      data-testid="lineup-slip"
      className="fixed bottom-5 right-5 z-50 w-72 rounded-2xl overflow-hidden shadow-2xl"
      style={{
        background: "hsl(222 47% 5%)",
        border: "1px solid hsl(258 90% 66% / 0.35)",
        boxShadow: "0 0 40px hsl(258 90% 66% / 0.12), 0 4px 32px rgba(0,0,0,0.6)",
      }}
    >
      {/* Header */}
      <div
        className="flex items-center gap-2 px-3 py-2.5 cursor-pointer select-none"
        style={{ background: "hsl(258 90% 66% / 0.1)", borderBottom: "1px solid hsl(258 90% 66% / 0.2)" }}
        onClick={() => setCollapsed(c => !c)}
      >
        <Layers className="w-3.5 h-3.5 shrink-0" style={{ color: "hsl(258 90% 75%)" }} />
        <span className="text-xs font-black tracking-wide" style={{ color: "hsl(258 90% 80%)" }}>
          MY LINEUP SLIP
        </span>
        <span
          className="ml-auto text-[9px] font-bold px-2 py-0.5 rounded-full shrink-0"
          style={{ background: "hsl(258 90% 66% / 0.2)", color: "hsl(258 90% 80%)", border: "1px solid hsl(258 90% 66% / 0.3)" }}
        >
          {picks.length}/6
        </span>
        <span className="text-muted-foreground ml-1 shrink-0">
          {collapsed ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
        </span>
      </div>

      {!collapsed && (
        <div className="p-2.5 space-y-2">
          {/* Picks list */}
          <div className="space-y-1.5">
            {picks.map(p => (
              <SlipRow key={p.id} pick={p} onRemove={() => onRemove(p.id)} />
            ))}
          </div>

          {picks.length < 6 && (
            <p className="text-[9px] text-muted-foreground text-center py-0.5">
              {6 - picks.length} more pick{6 - picks.length !== 1 ? "s" : ""} to fill the slip
            </p>
          )}

          {/* Export toggle */}
          <button
            data-testid="toggle-export"
            onClick={() => setShowExport(s => !s)}
            className="w-full flex items-center justify-center gap-1.5 py-2 rounded-xl text-xs font-bold transition-all hover:brightness-110 active:scale-[0.98]"
            style={{
              background: "linear-gradient(135deg, hsl(258 90% 60%), hsl(220 90% 55%))",
              color: "#fff",
            }}
          >
            <ExternalLink className="w-3 h-3" />
            Send to Platform
            {showExport ? <ChevronUp className="w-3 h-3 ml-auto" /> : <ChevronDown className="w-3 h-3 ml-auto" />}
          </button>

          {showExport && <ExportPanel picks={picks} />}

          {/* Clear */}
          <button
            data-testid="clear-slip"
            onClick={onClear}
            className="w-full flex items-center justify-center gap-1.5 py-1.5 rounded-xl text-[10px] font-semibold text-muted-foreground hover:text-red-400 transition-colors"
          >
            <Trash2 className="w-3 h-3" />
            Clear Slip
          </button>
        </div>
      )}
    </div>
  );
}
